buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -19,13 +19,20 @@ phases:
       - zip -r ../build-output.zip .
       - cd ..
       
-      # Find the dynamic deployment path and extract ZIP
+      # Find the dynamic deployment path
       - echo "Finding dynamic deployment path..."
-      - DEPLOYMENT_PATH=$(find /opt/codedeploy-agent/deployment-root -mindepth 2 -maxdepth 2 -type d -print -exec basename {} \; | head -n 1)
-      - DEPLOYMENT_ARCHIVE_PATH="/opt/codedeploy-agent/deployment-root/$DEPLOYMENT_PATH/d-*/deployment-archive"
-      - echo "Deployment archive path: $DEPLOYMENT_ARCHIVE_PATH"
-      - mkdir -p "$DEPLOYMENT_ARCHIVE_PATH"
-      - unzip build-output.zip -d "$DEPLOYMENT_ARCHIVE_PATH"
+      - |
+        DEPLOYMENT_PATH=$(find /opt/codedeploy-agent/deployment-root -mindepth 2 -maxdepth 2 -type d -print | grep -E 'd-[A-Z0-9]+$' | head -n 1)
+        if [ -z "$DEPLOYMENT_PATH" ]; then
+          echo "Error: Deployment path not found!"
+          exit 1
+        fi
+        DEPLOYMENT_ARCHIVE_PATH="$DEPLOYMENT_PATH/deployment-archive"
+        echo "Deployment archive path: $DEPLOYMENT_ARCHIVE_PATH"
+        
+        # Create the target directory and extract the ZIP file
+        mkdir -p "$DEPLOYMENT_ARCHIVE_PATH"
+        unzip build-output.zip -d "$DEPLOYMENT_ARCHIVE_PATH"
       
 artifacts:
   files:
